language: node_js
branches:
  only:
  - master
node_js:
- '8'
cache: yarn
install:
- npm i -g firebase-tools
- npm install -g @angular/cli
before_deploy:
- cd user-registration-app && npm install && ng build --prod && cd ..
deploy:
- provider: script
  script: bash scripts
  on:
    branch: master
env:
  global:
    secure: R3CpjgDRWimDZi4W0UfE4YWSaGq1OMCsI+STIxHVb0vLGPOFjEfLC544ocaiZesOLvNjaNCt2T03OVzv13Kd7od5wOwD+ylmSpLMcCZrErutxy8QSXCnI+fBRlZ81PF2JiS1ek3ibA59p3xTjkWG9jRp+K0YZnWQhnlfqWxHjCnyfm3E7he3OhGj8A0ZJefbY5RViN76PxMqhCS4qu2jY+aRpMKmEymHTe9SESRBdM9NtrtzGxV2Z8UOIs49JD0bTIt7qL/lTxEgXsoapKNMROk7/+g/qdDhUwOsrBw222g5yVqQzPaO2ekQ8jRSMpWI4JxcNzIBz2pOveNcJjSDjSwfyiLfY0jMmOFoQjFGZLZHAML8vUuZsBXCp7EFGyNRbo1Xv02rw6SB/2wE4k5IagFQKLeS9xnWOIK6hXo0RUrppofJc7F7TblhhvXKzU9gWADLTNcmpPBicmlWwt+7c1SKV8EGOR3AvDvYpTYnvHTuTYVTWgnMLeW/o97K9i6B86/6wfyjZIMQk7hsOemqz6Se+2+SS6ByJxHKAsDQYInqFdzeBOxGFRKFECLlctIlKEV9W/1nq7kcXx7ve7sRYbyWtjt3aaJFjbRHhfTwVGGez++TDvDHvEQ5dPxz9NcPLIVcpkYkLEnnLkwl9e560kgITS33xSQPXRzC5jVX4Es=
