language: node_js
node_js:
        - "node"
        - "9"
before_install:
install:
        - npm install
before_script:
script:
after_success:
        - cd api && eb deploy --profile hackpsu
after_failure:
after_script:
